{
  "action": {
    "error": {
      "variety": [
        "Loss"
      ],
      "vector": [
        "Unknown"
      ]
    }
  },
  "actor": {
    "internal": {
      "motive": [
        "NA"
      ],
      "variety": [
        "Unknown"
      ]
    }
  },
  "asset": {
    "assets": [
      {
        "variety": "M - Documents"
      }
    ]
  },
  "attribute": {
    "availability": {
      "variety": [
        "Loss"
      ]
    },
    "confidentiality": {
      "data": [
        {
          "amount": 100,
          "variety": "Medical"
        }
      ],
      "data_disclosure": "Yes",
      "data_victim": [
        "Patient"
      ],
      "state": [
        "Unknown"
      ]
    }
  },
  "discovery_method": "Unknown",
  "impact": {
    "overall_rating": "Unknown"
  },
  "incident_id": "74A41577-4A9E-4D55-A2CE-7B17A23FFFF8",
  "plus": {
    "analysis_status": "Finalized",
    "analyst": "Spitler",
    "attribute": {
      "confidentiality": {
        "credit_monitoring": "U"
      }
    },
    "created": "2016-10-19T14:49:00Z",
    "dbir_year": 2017,
    "github": "7734",
    "master_id": "2BA16C38-6E85-4106-9556-A48FC78A59CA",
    "modified": "2016-10-19T14:54:00Z",
    "sub_source": "phidbr",
    "timeline": {
      "notification": {
        "day": 28,
        "month": 4,
        "year": 2016
      }
    }
  },
  "reference": "http://www.independent.ie/irish-news/health/hospital-admits-it-lost-patients-test-results-data-34666948.html",
  "schema_version": "1.3.2",
  "security_incident": "Confirmed",
  "source_id": "vcdb",
  "summary": "Lost test results",
  "timeline": {
    "compromise": {
      "unit": "NA"
    },
    "exfiltration": {
      "unit": "NA"
    },
    "incident": {
      "year": 2016
    }
  },
  "victim": {
    "country": [
      "IE"
    ],
    "employee_count": "1001 to 10000",
    "industry": "622110",
    "region": [
      "150154"
    ],
    "victim_id": "Tallaght Hospital"
  }
}